replicaCount: 2

image:
  repository: ghcr.io/saquibfarash24/gitops-aks-demo
  pullPolicy: IfNotPresent
  tag: "194f44e5eec4506666724c84460ded4a0399a1fc"

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

containerPort: 8081

probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20


monitoring:
  serviceMonitor:
    enabled: true
